### ISSUE TITLE
boarder，快速开始一个webpack项目

### ISSUE THREAD

**Issue by shaodahong** [shaodahong/dahong#7]
现在许多的项目都是基于webpack来构建的，并且自从webpack提供了[中文官网](https://doc.webpack-china.org/)友好度大大的提高了，但是有些时候想快速开始一个webpack项目却只能把之前项目的一些config配置拿过来改改显得有点麻烦，所以写了一个简易的脚手架（真的很简易！！！）

安装：
```
$ npm install boarder -g
```

使用：
```
$ boarder init 项目名
```

初始化的结构目录是这样子的

**Comment by jamninetyfive** [comment]
多页应用 可以么?

**Comment by shaodahong** [comment]
@jamninetyfive 目前还未支持，不过下一个版本会支持的，请关注

**Comment by billyhero** [comment]
初始化报错，无法完成。
e:\webpack-boarder>boarder init my-project
run C:\Users\Administrator\.boarder-templates\my-project wdemo e:\webpack-boarde
r\my-project
err { RequestError
    at ClientRequest.req.once.err (C:\Users\Administrator\AppData\Roaming\npm\no
de_modules\boarder\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:400:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  message: 'unable to verify the first certificate',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/shaodahong/wdemo/archive/master.zip',
  bufferedData: <Buffer > }

**Comment by shaodahong** [comment]
@billyhero 像是网络原因，你是不是开了代理什么的

**Comment by billyhero** [comment]
@shaodahong 没有开代理的，我再重新安装一下boarder试一下看看。

**Comment by shaodahong** [comment]
@billyhero 恩，报错的原因大概的意思就是你的网络访问https报错 ，可以看看这里的[解决办法](https://github.com/p2227/p2227.github.io/issues/5)

**Comment by billyhero** [comment]
@shaodahong npm config set strict-ssl=false 然后再注销一下电脑，现在可以下载了。谢谢~~

**Comment by shaodahong** [comment]
@billyhero 恩，好了就行
